### REQUIRED
# The namespace of the collection. This can be a company/brand/organization or product namespace under which all
# content lives. May only contain alphanumeric lowercase characters and underscores. Namespaces cannot start with
# underscores or numbers and cannot contain consecutive underscores
namespace: intellium

# The name of the collection. Has the same character restrictions as 'namespace'
name: rancher
version: 0.0.7
readme: README.md
authors:
  - Wouter Moeken <wouter@moeken.eu>
description: Rancher Cluster management
license:
  - GPL-2.0-or-later
tags: []
dependencies: {}
repository: http://github.com/intellium/ansible-collection-rancher
documentation: http://github.com/intellium/ansible-collection-rancher
homepage: http://github.com/intellium/ansible-collection-rancher
issues: https://github.com/Intellium/ansible-collection-rancher/issues

build_ignore:
  - "*.tar.gz"
